apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-deployment
  labels:
    app: complete-production-e2e-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complete-production-e2e-app
  template:
    metadata:
      labels:
        app: complete-production-e2e-app
    spec:
      containers:
      - name: complete-production-e2e-app
        image: abuchijoe/complete-production-e2e-pipeline:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
