apiVersion: v1
kind: Service
metadata:
  name: terraform-pipeline-production-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: terraform-pipeline-production
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP