apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: complete-production-e2e
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31918
      protocol: TCP